# backend:
#   name: git-gateway
#   branch: main # ou a branch do seu projeto

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "landing_page"
    label: "Landing Page"
    folder: "src/content"
    create: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Texto Principal", name: "body", widget: "text" }
      - { label: "Imagem", name: "image", widget: "image" }

backend:
  name: test-repo # Backend temporário para teste local
  branch: main # Branch do Git
