backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads" # Diretório onde as imagens serão armazenadas
public_folder: "/images/uploads" # Caminho público para as imagens

collections:
  - name: "conteudo"
    label: "Conteúdo"
    files:
      - label: "Página Inicial"
        name: "pagina_inicial"
        file: "src/data/pagina_inicial.json" # Localização do arquivo de dados
        fields:
          - { label: "Título", name: "titulo", widget: "string" }
          - { label: "Descrição", name: "descricao", widget: "text" }
          - { label: "Imagem", name: "imagem", widget: "image" }
